pipeline {
    agent { 
        dockerfile {
            dir 'tests'
            filename 'Dockertest'
        }
    }
    stages {
        stage('Unit Tests') {
            steps {
                dir('tests') {
                    sh 'python3 test_sherlock_wrapper.py'
                }
            }
        }
    }
}

