pipeline {
    agent { dockerfile true }
    stages {
        stage('Unit Tests') {
            steps {
                sh '''which python
                      python --version
                      cd tests/unit/pipeline/sherlock
                      python test_sherlock_wrapper.py
                   '''
            }
        }
    }
}

